In [ ]:
# This Python 3 environment comes with many helpful analytics libraries installed
# It is defined by the kaggle/python Docker image: https://github.com/kaggle/docker-python
# For example, here's several helpful packages to load

import numpy as np # linear algebra
import pandas as pd # data processing, CSV file I/O (e.g. pd.read_csv)

# Input data files are available in the read-only "../input/" directory
# For example, running this (by clicking run or pressing Shift+Enter) will list all files under the input directory

import os
for dirname, _, filenames in os.walk('/kaggle/input'):
    for filename in filenames:
        print(os.path.join(dirname, filename))

# You can write up to 20GB to the current directory (/kaggle/working/) that gets preserved as output when you create a version using "Save & Run All" 
# You can also write temporary files to /kaggle/temp/, but they won't be saved outside of the current session

# **Initialization**
* Importing libraries needed
* Initializing the test cases mentioned in the assignment

In [1]:
import numpy as np
from scipy.special import multigammaln

covariance_matrix = np.array([[4.3, -0.1, 0.7, 1.2, -0.5, 0.4],[-0.1, 3.8, 0.3, 0.9, 0.2, 0.1],[0.7, 0.3, 5.5, -0.3, 0.8, -0.2],[1.2, 0.9, -0.3, 6.1, 0.1, -0.6],[-0.5, 0.2, 0.8, 0.1, 4.7, 0.5
],[0.4, 0.1, -0.2, -0.6, 0.5, 3.9]])
mean = np.array([1.5, 2.8, -0.6, 4.1, -1.0, 3.2])
p = mean.shape[0]
print("number of variables: ",p)
print("mean: ", mean)
print("covariance_matrix:\n", covariance_matrix)

number of variables:  6
mean:  [ 1.5  2.8 -0.6  4.1 -1.   3.2]
covariance_matrix:
 [[ 4.3 -0.1  0.7  1.2 -0.5  0.4]
 [-0.1  3.8  0.3  0.9  0.2  0.1]
 [ 0.7  0.3  5.5 -0.3  0.8 -0.2]
 [ 1.2  0.9 -0.3  6.1  0.1 -0.6]
 [-0.5  0.2  0.8  0.1  4.7  0.5]
 [ 0.4  0.1 -0.2 -0.6  0.5  3.9]]


# **Question 1: Multivariate Normal Distribution Generation**
1. Write a Python function that generates n samples from a multivariate
normal distribution with a given mean vector µ and covariance matrix Σ.
Your function should return a NumPy array where each row represents a
sample.

In [2]:
def generate_multivariate_samples(n, mean, covariance_matrix):
    """
    It generates n samples from a multivariate normal distribution.

    Args:
        n: Number of samples to generate.
        mean : Mean vector of the distribution.
        covariance_matrix : Covariance matrix of the distribution.

    Returns:
        An list with 'n' rows, each representing a sample.
    """
    samples = np.random.multivariate_normal(mean, covariance_matrix, n)
    return samples

# **Test Section**

In [3]:
n_samples = 10
generated_samples = generate_multivariate_samples(n_samples, mean, covariance_matrix)
print(f"{n_samples} samples of multivariate normal distribution with given mean and covariance matrix\
      \n",generated_samples)

10 samples of multivariate normal distribution with given mean and covariance matrix      
 [[-0.38568695  3.599549   -1.37553542  4.53717714  1.14766664  6.01685235]
 [ 2.61417128  5.01198554  1.0493578   2.27577044 -1.43977375  1.80566258]
 [ 2.81949073  6.47583241  2.0134018   2.59720442 -1.22853521  3.41901326]
 [-0.77203803  3.08443532  0.21467847  4.61823405  0.42166692  3.69398089]
 [ 1.61460486  3.79210468 -0.52806376  3.18339086 -1.7954716   4.0077386 ]
 [ 3.70724916  5.74164024  4.24606566  6.94186411 -0.78170147  2.46845965]
 [ 0.95020821  1.92224086  1.48240527  7.39754801  1.23081244  4.68791268]
 [-2.92338168  2.78505191 -2.42570397 -0.87963068 -0.57104254  3.29605413]
 [ 3.75083806  1.75099658 -0.43087162 -0.54881285  0.39066283  2.76647437]
 [-0.861219    4.97954673  1.78858133  2.35922136  0.31552465  4.12555693]]


# **Question 2: Distribution Properties**

Write Python functions to calculate the following properties for the generated
samples. The sample mean and sample variance-covariance matrix should be
calculated from scratch without using direct functions available in numpy for
computation. Specifically functions like np.mean and np.cov are not allowed.

1. Mean Vector: Write a function to compute the sample mean vector.
2. Covariance Matrix: Write a function to calculate the sample covariance
matrix.
3. Moment Generating Function: Write a function that computes the moment generating function of the distribution for a given t.

### Mean (Expectation):
The mean of a multivariate sample is given by the formula:

$$
\mu = \frac{1}{n} \sum_{i=1}^{n} X_i
$$

Where: \
$\mu$ is the mean vector. \
$n$ is the number of samples. \
$X_i$ is the i-th sample.
### Covariance Matrix:
The covariance matrix for a multivariate sample is given by the formula:

$$
Σ = \frac{1}{n-1} (X - \mu)^T (X - \mu)
$$

Where: \
$Σ$ is the covariance matrix. \
$n$ is the number of samples. \
$X$ is the miltuvariate normal sample. \
$\mu$ is the mean vector.

#### Moment Generating Function (MGF):
The Moment Generating Function for a multivariate sample is calculated as follows:

$$
\text{MGF}(t) = e^{(t^T \mu + 0.5 \cdot t^T Σ \cdot t)}
$$

Where:
$\text{MGF}(t)$ is the Moment Generating Function at $t$.\
$t$ is the input vector.\
$\mu$ is the mean vector.\
$Σ$ is the covariance matrix.\


In [4]:
def get_mean_covariance_matrix_mgf(sample, mean , covariance_matrix, t):
    """
    Calculate the mean, covariance matrix, and MGF of a multivariate sample.

    Args:
        sample (numpy.ndarray): Multivariate normal distribution sample.
        t (numpy.ndarray): Input to calculate the Moment Generating Function (MGF).

    Returns:
        tuple: A tuple containing three elements - mean, covariance matrix, and MGF at the given t.
    """
    n, p = sample.shape  # Get the dimensions of the sample
    sample_mean = np.zeros(p)  # Initialize the mean vector with zeros
    for i in range(n):
        sample_mean = sample_mean + sample[i, :]  # Calculate the sum of sample rows
    sample_mean = sample_mean / n  # Calculate the mean

    # Calculate the covariance matrix using formula mentioned in markdown
    cov = ((sample - mean).T @ (sample - mean)) / (n - 1)

    # Calculate the Moment Generating Function (MGF) using formula mentioned in markdown
    mgf = np.exp(t.T @ mean + 0.5 * (t.T @ covariance_matrix @ t))

    return sample_mean, cov, mgf  # Return the mean, covariance matrix, and MGF


# **Test Section**

In [5]:
t = np.random.random((6,1))

sample_mean, cov, mgf = get_mean_covariance_matrix_mgf(generated_samples,mean , covariance_matrix, t)
print("Mean of the sample:", sample_mean)
print("Covariance matrix of the sample:\n", cov)
print("MGF at t of the sample:", mgf)

Mean of the sample: [ 1.05142366  3.91433833  0.60343156  3.24819669 -0.23101911  3.62877054]
Covariance matrix of the sample:
 [[ 5.23285470e+00  5.34291712e-01  1.91931053e+00  1.55676395e+00
  -1.19786414e+00 -1.51387508e+00]
 [ 5.34291712e-01  3.93153797e+00  3.38013626e+00 -3.72153403e-01
  -4.38243740e-02 -8.04985557e-03]
 [ 1.91931053e+00  3.38013626e+00  5.30094060e+00  1.98519775e+00
   7.12269052e-01 -2.15110492e-01]
 [ 1.55676395e+00 -3.72153403e-01  1.98519775e+00  8.36384201e+00
   7.06734683e-02  6.34993435e-01]
 [-1.19786414e+00 -4.38243740e-02  7.12269052e-01  7.06734683e-02
   1.82052715e+00  1.16533465e+00]
 [-1.51387508e+00 -8.04985557e-03 -2.15110492e-01  6.34993435e-01
   1.16533465e+00  1.62512461e+00]]
MGF at t of the sample: [[70794.18521608]]


# **Question 3: Conditional Distribution**
1. Write a Python function that calculates the conditional distribution of
the i-th variable given the other variables. The function should return the
mean vector and covariance matrix of the conditional distribution. In the
test section try this function for each variable in the multivariate normal
distribution, evaluated at the value of remaining variables according to
any of the generated samples.

Let $X$ be the $i_{th}$ variable and $Y$ be the multivariate distribution of the other variables. Then conditional distribution of $X$ given $Y = y$ is normal with
$$Mean = \mu_X + Σ_{XY}\cdot (Σ_{YY})^{-1} \cdot(y - \mu_Y) $$ \
$$Covarinace = Σ_{XX} - Σ_{XY}(Σ_{YY})^{-1}Σ_{YX}$$

In [6]:

def conditional_distribution(mean, cov_matrix, sample, i):
    """
    Calculate the conditional distribution of the i-th variable given the other variables in a multivariate distribution.
    Args:
        mean: Mean vector of the distribution.
        cov_matrix : Covariance matrix of the distribution.
        sample : A multivariate normal distribution sample.
        i: Index of the variable for which the conditional distribution is calculated.

    Returns:
        tuple: A tuple containing the mean vector and covariance matrix of the conditional distribution.
    """
    # Swap rows and columns for mean and covariance matrix
    mean[[0, i]] = mean[[i, 0]]
    cov_matrix[[0, i], :] = cov_matrix[[i, 0], :]
    cov_matrix[:, [0, i]] = cov_matrix[:, [i, 0]]
    sample[[0, i]] = sample[[i, 0]]

    # Extract variables
    y = sample[1:]
    mu_x = mean[0]
    mu_y = mean[1:]

    sigma_xx = cov_matrix[0, 0]
    sigma_xy = cov_matrix[0, 1:]
    sigma_yx = cov_matrix[1:, 0]
    sigma_yy = cov_matrix[1:, 1:]

    # Calculate the conditional distribution mean and covariance
    # np.linalg.inv calculates the inverse of the matrix
    conditional_mean = mu_x + sigma_xy @ np.linalg.inv(sigma_yy) @ (y - mu_y)
    conditional_covariance = sigma_xx - sigma_xy @ np.linalg.inv(sigma_yy) @ sigma_yx

    return conditional_mean, conditional_covariance




# **Test Section**

In [7]:

generated_samples = generate_multivariate_samples(n_samples, mean, covariance_matrix)
for i in range(p):
    conditional_mean, conditional_covariance = conditional_distribution(mean.copy(), covariance_matrix.copy(), generated_samples[0], i)
    print(f"Conditional Mean for variable {i}: {conditional_mean}")
    print(f"Conditional Covariance for variable {i}: {conditional_covariance}\n")

Conditional Mean for variable 0: 2.4348472581911973
Conditional Covariance for variable 0: 3.737080956512091

Conditional Mean for variable 1: 2.8728927564407747
Conditional Covariance for variable 1: 3.6022064462777243

Conditional Mean for variable 2: -1.209747035540981
Conditional Covariance for variable 2: 5.073815600551377

Conditional Mean for variable 3: 2.5537053579009155
Conditional Covariance for variable 3: 5.287134197788683

Conditional Mean for variable 4: -1.2960668203558416
Conditional Covariance for variable 4: 4.373096842185152

Conditional Mean for variable 5: 2.8322181875606836
Conditional Covariance for variable 5: 3.6506645856203526



In [8]:

generated_samples = generate_multivariate_samples(n_samples, mean, covariance_matrix)
for i in range(p):
    conditional_mean, conditional_covariance = conditional_distribution(mean.copy(), covariance_matrix.copy(), np.array([0,1,2,3,4,5]), i)
    print(f"Conditional Mean for variable {i}: {conditional_mean}")
    print(f"Conditional Covariance for variable {i}: {conditional_covariance}\n")

Conditional Mean for variable 0: 1.3880746225960587
Conditional Covariance for variable 0: 3.737080956512091

Conditional Mean for variable 1: 3.103607738511954
Conditional Covariance for variable 1: 3.6022064462777243

Conditional Mean for variable 2: -0.19878790220645293
Conditional Covariance for variable 2: 5.073815600551377

Conditional Mean for variable 3: 2.860183898560367
Conditional Covariance for variable 3: 5.287134197788683

Conditional Mean for variable 4: -0.06689723415665583
Conditional Covariance for variable 4: 4.373096842185152

Conditional Mean for variable 5: 3.46061856568199
Conditional Covariance for variable 5: 3.6506645856203526



# **Question 4: Mahalanobis Distance**
1. Mahalanobis Distance: Write a function that calculates the Mahalanobis
distance between each sample and the mean vector µ.

For a multivariate sample $\mathbf{x}$ and mean vector $\mathbf{\mu}$ with a covariance matrix $\mathbf{\Sigma}$, the Mahalanobis distance $d$ is calculated as:

$$d = \sqrt{(\mathbf{x} - \mathbf{\mu})^T \cdot \mathbf{\Sigma}^{-1} \cdot (\mathbf{x} - \mathbf{\mu})}$$

Where:
- $\mathbf{x}$ is the sample vector.
- $\mathbf{\mu}$ is the mean vector.
- $\mathbf{\Sigma}$ is the covariance matrix.
- $\mathbf{\Sigma}^{-1}$ is the inverse of the covariance matrix.
- $d$ is the Mahalanobis distance.


In [9]:
def mahalanobis_distance(samples, mean, covariance_matrix):
    """
    Calculate the Mahalanobis distance between each sample and the mean vector.

    Args:
        samples (numpy.ndarray): Multivariate samples, where each row represents a sample.
        mean (numpy.ndarray): Mean vector of the multivariate distribution.
        covariance_matrix (numpy.ndarray): Covariance matrix of the multivariate distribution.

    Returns:
        numpy.ndarray: An array containing the Mahalanobis distances for each sample.
    """
    n = samples.shape[0]
    inv_cov_matrix = np.linalg.inv(covariance_matrix)  # Inverse of the covariance matrix
    distances = []
    for i in range(n):
        diff = samples[i,:] - mean  # Differences between each sample and the mean
        distances.append(np.sqrt(diff@inv_cov_matrix@diff.T)) #Applying the formula for each sample

    return distances




# **Test Section**

In [10]:
# Calculate Mahalanobis distances for each sample
distances = mahalanobis_distance(generated_samples, mean.copy(), covariance_matrix.copy())

# Print Mahalanobis distances for each sample
for i, distance in enumerate(distances):
    print(f"Mahalanobis Distance for Sample {i + 1}: {distance:.4f}")


Mahalanobis Distance for Sample 1: 2.2585
Mahalanobis Distance for Sample 2: 2.0610
Mahalanobis Distance for Sample 3: 2.7140
Mahalanobis Distance for Sample 4: 1.9842
Mahalanobis Distance for Sample 5: 2.2768
Mahalanobis Distance for Sample 6: 3.2434
Mahalanobis Distance for Sample 7: 1.7244
Mahalanobis Distance for Sample 8: 1.5883
Mahalanobis Distance for Sample 9: 2.9200
Mahalanobis Distance for Sample 10: 4.0170


# **Question 5: Sampling from Wishart Distribution**
1. Write code to sample from a Wishart Distribution from scratch, including density and sampling functions. Specifically you cannot directly use
scipy.stats.wishart. Other functionalities from scipy and numpy can
be used. Write a function to generate samples from the Wishart distribution with specified degrees of freedom and scale matrix.
2. Implement a function to calculate the Hotelling’s T
2
statistic for a given
set of multivariate data.

The Wishart distribution is a multivariate generalization of the chi-squared distribution. To calculate the Wishart density for a given matrix $X$, degrees of freedom $\nu$, and scale matrix $V$, we can use the following formula:

$$
f(X|\nu, V) = \frac{{|X|^{\frac{{\nu - p - 1}}{2}} \exp\left(-\frac{1}{2}\text{tr}(V^{-1}X)\right)}}{{2^{\frac{{\nu p}}{2}} |V|^{\frac{\nu}{2}} \Gamma_p\left(\frac{\nu}{2}\right)}}
$$

Where:
- $X$ is the matrix for which we want to calculate the density.
- $\nu$ is the degrees of freedom.
- $V$ is the scale matrix.
- $p$ is the dimension of $X$.
- $|X|$ is the determinant of $X$.
- $\text{tr}(A)$ is the trace of matrix $A$.
- $|V|$ is the determinant of the scale matrix $V$.
- $\Gamma_p(\cdot)$ is the multivariate gamma function.

**Sampling from Wishart Distribution**

To sample from the Wishart distribution with specified degrees(dof) of freedom and scale matrix, we follow:

1. Generate $dof$ independent standard multivariate normal variables $X_1, X_2, \ldots, X_{dof}$ where $X_i \sim N(0, \Sigma)$  
2. Compute $\sum_{i=1}^{dof} X_i\cdot X_i^T$

This is one sample of wishart distribution of specified parameters


### Part 2

Let S be the sample covariance of the matrix, <br>
$$
S = \frac{\sum_{i=1}^{n}(X_{i} - \bar{X})(X_{i} - \bar{X})^T}{n-1}
$$,
where each $X_{i}$ is the ith sample of dimension $(p \times 1)$<br>
The Hotelling-$T^2$ statistic is given by, <br>
$$
T^{2} = n(\bar{X} - \mu)^{T}(S)^{-1}(\bar{X} - \mu)
$$

In [11]:
def wishart_density(X, nu, V):
    """
    Calculate the Wishart density for a given matrix X, degrees of freedom nu, and scale matrix V.
    Returns: The Wishart density.
    """
    p = X.shape[0]  # Get the dimension (number of rows) of the matrix X

    det_X = np.linalg.det(X)  # Calculate the determinant of matrix X
    det_V = np.linalg.det(V)  # Calculate the determinant of the scale matrix V

    tr_invVX = np.trace(np.linalg.inv(V) @ X)  # Calculate the trace of the product of the inverse of V and X

    term1 = det_X**((nu - p - 1) / 2)  # Calculate the first term of the density formula
    term2 = np.exp(-0.5 * tr_invVX)  # Calculate the second term of the density formula
    term3 = (
        2**((nu * p) / 2) * det_V**(nu / 2) *\
        np.exp(multigammaln(nu / 2, p))  # Calculate the multivariate gamma function\
    )

    # Calculate the Wishart density using the three terms
    density = (term1 * term2) / term3

    return density  # Return the calculated Wishart density

    
def sample_wishart(dof, scale_matrix, n):
    """
    Generate n samples from the Wishart distribution with specified degrees of freedom and scale matrix.
    Returns:
    list of numpy.ndarray: List of Wishart-distributed samples.
    """
    p = scale_matrix.shape[0]  # Dimension
    mean = np.zeros(p)
    samples = []  # List to store generated samples

    for _ in range(n):
        # Step 1: Generate 'dof' independent standard multivariate normal variables
        X = generate_multivariate_samples(dof, mean, scale_matrix)
        # Step 2: Compute the Wishart-distributed sample
        sample = X.T @ X
        samples.append(sample)

    return samples

def hotelling_T2(X, mean):
    """
    Input : X - sample matrix of size n x p
    mean : mean of the wishart distribution
    """
    n = X.shape[0]
    p = X.shape[1]
    sample_mean,sample_covariance,_ = get_mean_covariance_matrix_mgf(X , mean , covariance_matrix,np.zeros(p)) # calculating sample mean and covariance_matrix
    #here 0 is dummy , as we do not need mgf
    d = sample_mean - mean
    statistic =  n * ((d.T @ np.linalg.inv(sample_covariance)) @ d) # calculating value of statistic as per above description
    return statistic


# **Test Section**

In [12]:
# Example usage:
dof = 10
scale_matrix = covariance_matrix
n_samples = 3

# Generate Wishart-distributed samples
wishart_samples = sample_wishart(dof, scale_matrix, n_samples)

# Print the generated samples
for i, sample in enumerate(wishart_samples):
    print(f"Sample {i + 1}:\n{sample}")

# Calculate the Wishart density for a sample
for i in range(n_samples):
    sample_to_calculate_density = wishart_samples[i]
    nu = dof
    V = scale_matrix
    density = wishart_density(sample_to_calculate_density, nu, V)
    print(f"Wishart Density for Sample {i}: {density}")
    
    
T2 = hotelling_T2(generated_samples, mean)
print("Hotelling T2 statistic for generated_samples of given mean is: ",T2)

Sample 1:
[[ 59.5996802    6.97325524  14.94423004  -9.60927761 -19.03355689
   -1.83858505]
 [  6.97325524  61.48426232 -11.0993078    3.07124082  -6.74511106
   -5.7717845 ]
 [ 14.94423004 -11.0993078   44.17487702 -17.46789232  -8.34632845
   -5.02731417]
 [ -9.60927761   3.07124082 -17.46789232  34.85945226   8.15981327
    5.60281009]
 [-19.03355689  -6.74511106  -8.34632845   8.15981327  58.76786067
   -2.10302388]
 [ -1.83858505  -5.7717845   -5.02731417   5.60281009  -2.10302388
    3.98783352]]
Sample 2:
[[ 32.2119305   12.15855019  -2.47388739  34.51444139  -6.02197502
    3.78316882]
 [ 12.15855019  16.15437788  -4.49146613  34.4492274   -4.56186822
    8.64261055]
 [ -2.47388739  -4.49146613  28.39326388 -14.70966127   2.19260034
    0.35624832]
 [ 34.51444139  34.4492274  -14.70966127  97.14025573  -9.95830817
   16.05006888]
 [ -6.02197502  -4.56186822   2.19260034  -9.95830817  67.59115093
    0.64288855]
 [  3.78316882   8.64261055   0.35624832  16.05006888   0.64288855

# **Question 6: Sampling Distribution**
1. Write a Python function to compute the distribution of the sample mean
for the multivariate normal distribution. Generate samples from this distribution. You can use previously defined functions

Given data vectors $X_1, X_2, ..., X_n$ from a multivariate normal distribution with mean $μ$ and covariance $Σ$, the distribution of the sample mean, denoted as $\bar{X}$, is also a multivariate normal distribution. It retains the original mean $μ$, but its covariance matrix is scaled by $1/n$, i.e $\bar{X}$ follows $N_p(μ, Σ/n)$, where $p$ is the dimension of the data.

In [13]:
def sample_mean(n, mean, covariance_matrix):
    """
    Generate samples from the distribution of the sample mean of a multivariate normal distribution.

    Args:
    n: Number of samples to generate.
    mean: Mean vector of the multivariate normal distribution.
    cov: Covariance matrix of the multivariate normal distribution.

    Returns:
    list of numpy.ndarray: List of sample mean samples.
    """
    mean_cov = covariance_matrix / n  # Calculate the covariance matrix for the sample mean distribution
    samples = generate_multivariate_samples(n , mean, mean_cov)  # Generate samples of multivariate normal distribution
    return samples

# **Test section**

In [14]:
n = 10
mean_samples = sample_mean(n, mean, covariance_matrix)
for i in range(n):
    print(f"Sample {i} from a mean distribution:\n", mean_samples[i])
    print()

Sample 0 from a mean distribution:
 [ 2.51328387  3.09754924 -0.46348843  5.65731751  0.76564553  3.92017224]

Sample 1 from a mean distribution:
 [ 1.88787873  2.92352084 -0.4899689   5.1756488  -0.31315727  2.81845231]

Sample 2 from a mean distribution:
 [ 1.38006624  3.42390814 -0.05105396  3.59560994 -0.70471796  2.82298695]

Sample 3 from a mean distribution:
 [ 1.36455795  3.13289631 -0.03799148  3.58840791 -0.69156019  3.2494464 ]

Sample 4 from a mean distribution:
 [ 1.32304233  2.93104979  0.03957878  3.15013508 -1.47640383  2.67633342]

Sample 5 from a mean distribution:
 [-0.3299241   2.06303472 -0.91094335  4.11220097 -1.31810893  2.57433972]

Sample 6 from a mean distribution:
 [ 0.85855193  3.41432141 -1.59904066  4.1229665  -2.25420204  3.02501421]

Sample 7 from a mean distribution:
 [ 0.97714762  3.35342093 -1.27782624  4.17315221 -0.69639018  2.50737707]

Sample 8 from a mean distribution:
 [1.87857863 3.21837154 0.13251236 4.97692775 0.27968645 3.35893548]

Sample 